# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{docusignsdk}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nicholas reed"]
  s.date = %q{2011-08-28}
  s.description = %q{DocuSign Ruby Gem}
  s.email = %q{nicholas.a.reed@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "docusignsdk.gemspec",
    "lib/Credential.wsdl",
    "lib/docusign.rb",
    "lib/docusign/anchor_tab.rb",
    "lib/docusign/auth_header_handler.rb",
    "lib/docusign/base.rb",
    "lib/docusign/builder/anchor_builder.rb",
    "lib/docusign/builder/base.rb",
    "lib/docusign/builder/tab_builder.rb",
    "lib/docusign/credential.rb",
    "lib/docusign/credentialDriver.rb",
    "lib/docusign/credentialMappingRegistry.rb",
    "lib/docusign/document.rb",
    "lib/docusign/docusign.rb",
    "lib/docusign/docusignDriver.rb",
    "lib/docusign/docusignMappingRegistry.rb",
    "lib/docusign/extensions.rb",
    "lib/docusign/integrators_key_auth_header_handler.rb",
    "lib/docusign/request_recipient_token_client_urls.rb",
    "lib/docusign/tab.rb",
    "lib/docusign/utilities.rb",
    "lib/docusignsdk.rb",
    "lib/wsdl/DocuSign3.0.10API.wsdl",
    "lib/wsdl/DocuSign3.0.11API.wsdl",
    "lib/wsdl/DocuSign3.0.2API.wsdl",
    "lib/wsdl/DocuSign3.0.2CredentialAPI.wsdl",
    "test/helper.rb",
    "test/test_docusignsdk.rb"
  ]
  s.homepage = %q{http://github.com/nicholasareed/docusignsdk}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DocuSign Ruby Gem}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

